##### PAGE BREAK

```{r tabcategorization}
tab_categorization %>%
  ungroup() %>% 
  mutate(
    `Comorbidities by groups` = 
      gsub("Heart infarct", "Myocardial infarction", `Comorbidities by groups`)
  ) %>% 
  knitr::kable(
    caption = "Categorization of co-morbidities based on diagnostic groups according to Charlson and Elixhauser. (CNS = central nervous system.)")

```

##### PAGE BREAK

```{r tab1}

load("../cache/table1_infection.RData")

knitr::kable(
  mutate(table1_infection$table1, what = gsub("Heart infarct", "Myocardial infarction", what)), 
  caption = "Characteristics of the study population in the model derivation cohort (SHAR). Educational levels were classified as low (up to 9 years), middle (10-12 years) and high (at least 12 years). BMI = Body mass index. ASA = American Society for Anesthesiologists classification. CNS = central nervous system.")
```

##### PAGE BREAK

```{r brlprop}
model_data <- readRDS("../cache/model_data.rds")

model_data %>% 
  select(outcome, time, coefs_selected) %>% 
  mutate(coefs_selected = map(coefs_selected, "brlasso_tbl_selected")) %>% 
  unnest("coefs_selected") %>%
  filter(outcome == "infection") %>% 
  select(-outcome) %>% 
  pivot_wider(names_from = "time", values_from = "n") %>% 
  mutate(
    variable = clean_names(variable) %>% 
      {gsub("\\.", " ", .)} %>% 
      {gsub("Rheumatidisease", "Rheumatic disease", .)} %>% 
      {gsub("Diagnos", "Diagnosis:", .)}
  ) %>% 
  select(Predictor = variable, `90 days` = `90d`, `2 years` = `2y`) %>% 
knitr::kable(
  caption = "Variables selected by the bootstrap ranking procedure, and therefore kept in the main model. Variables chosen at least 75 times out of 100 were kept in the reduced model as well. (CNS = central nervous system.)")
```

##### PAGE BREAK

```{r brlreduced}

load("../cache/tbl_coefs.RData")

tbl_coefs %>% 
  filter(outcome == "infection") %>% 
  select(-outcome, -Model, -math) %>% 
  mutate(
    time = replace(as.character(time), duplicated(time), ""),
    beta = round(beta, 2)
  ) %>% 
knitr::kable(
  caption = 'Estimated coefficients (beta) and odds ratios (OR) with 95 % confidence intervals for the reduced model.'
)
```
